sudo: required
dist: trusty
language: python
python:
        - 3.5
        - 3.4
        - 3.3
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y python3-setuptools
script: python3 setup.py install
notifications:
        email: false
