language: python
python:
        - 3.5
os:
        - linux
branches:
        only:
                - master
sudo: required
dist: trusty
notifications:
        email: false
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y python3-setuptools
script: python3 setup.py install
